### ISSUE TITLE
add quick summary for data table

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/minimal-edi-package#1]
see protocol 10.2
use R summary function, example https://github.com/WHOIGit/nes-lter-npp-transect/blob/main/npp-transect-eml-assembly.Rmd#L91

**Comment by sbeaulieu** [comment]
I think use of summary function will be even better if convert from character to factor those columns that use categorical variables

**Comment by joefutrelle** [comment]
@sbeaulieu the linked line seems irrelevant?

This one seems more relevant https://github.com/WHOIGit/nes-lter-npp-transect/blob/7ff8417e619f35b2b1964af00865f0254eb73dd2/npp-transect-eml-assembly.Rmd#L171

**Comment by sbeaulieu** [comment]
@joefutrelle you are correct (in the future I will try to link with commit in the URL)

**Comment by joefutrelle** [comment]
no problem, I'm curious as to why GitHub is currently not rendering the lines being referenced--I thought it always did that

**Comment by joannekoch** [comment]
I think it's because the code changes and the line numbers change. It's not a good idea to reference line numbers for this reason.  It's better to paste a snippet of the code your are referencing.

**Comment by joefutrelle** [comment]
@joannekoch if you select "Copy Permalink" when referencing a line, you get the line from the commit you're viewing, which solves the problem you're talking about. Better to use these references than copypasting code, see [this comment](https://github.com/WHOIGit/nes-lter-ims/issues/57#issue-1632691888) for an example of GitHub rendering the lines--why isn't this working here? 😕

**Comment by joefutrelle** [comment]
@sbeaulieu back to the issue, shouldn't the responsibility for treating some columns as categorical and some as character be on the data table provider, and not on the chunk that produces a summary?

**Comment by sbeaulieu** [comment]
yes the provider determines the columns that are categorical. however the distinction bw character and factor is the way 'R' is interpreting the csv data table. I like your idea of just declaring all character columns as factor for the summary

**Comment by joefutrelle** [comment]
@sbeaulieu can you clarify? In my solution the summary is applied to the provided data table and in my view the provider should, after reading the CSV data or generating the table via some workflow, declare the categorical columns as categorical--and then the summary will do the right thing.

**Comment by sbeaulieu** [comment]
ok if you would like to just use the columns associated to categorical variables, then run the summary after generating the catvars txt from the -info xlsx CategoricalVariables tab

**Comment by joefutrelle** [comment]
I don't get it. Shouldn't the table already have those columns represented as factors, *before* we get to the summary stage? I don't like the idea of mixing data manipulation with data summarization, and if we have categorical variables that are represented as character columns in R, then we're not tending to our column types in our workflows as we should be.

**Comment by sbeaulieu** [comment]
discuss character columns as factor for the summary because helpful even for those columns that are not associated to categorical variables
