### ISSUE TITLE
inspect character columns as factor in summary 

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/minimal-edi-package#11]
I suggest including this additional code in the summary chunk in the minimal template to be able to manually inspect the character columns as factor columns in the summary
https://github.com/WHOIGit/nes-lter-zooplankton-transect-abundance/commit/7d584be7103dd199ebc930b3e08c1d9d18dfcbe7

**Comment by katemorkeski** [comment]
looks good on visual inspection!

**Comment by katemorkeski** [comment]
confirmed this code works well in growth-grazing-chl workflow
