### ISSUE TITLE
need to be able to replace intellectual_rights.txt template

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/minimal-edi-package#12]
It appears that if I generate an intellectual_rights.txt template at first using the argument CC0 for excel_to_template that if I subsequently change that argument to CCBY that I cannot replace the intellectual_rights.txt with CCBY.
If I delete the rights with CC0 and run excel_to_template with CCBY argument then it works.
We should have the flexibility to switch between these options when iterating the package thanks

**Comment by joannekoch** [comment]
`excel_to_template` calls `EMLassemblyline::template_core_metadata` to handle the creation of intellectual_rights.txt.

`EMLassemblyline::template_core_metadata` has a parameter _**write.file**_ which is defaulted to TRUE. The _write.file_ parameter does not work as one would think. The code for `template_core_metadata` only writes to files that already do NOT exist. 

The recommended solution to this issue would be to delete intellectual_rights.txt in `excel_to_template` (in ediutilities) before the call to `EMLassemblyline::template_core_metadata.`

This change will be made to `ediutilities` and not the minimal edi package. This issue will be closed and a new issue opened in `ediutilities`.
