### ISSUE TITLE
add Taylor to personnel

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/minimal-edi-package#2]
add Taylor to personnel in nes-lter-minimal-info.xlsx
instead of First Name E. Taylor: it needs to be First Name E. Middle Name: Taylor.

**Comment by joannekoch** [comment]
@sbeaulieu, this table has the heading for Column B as middleInitial and not middleName.
Can we put a middle name in the middle initial column?

![Capture](https://user-images.githubusercontent.com/65416034/220716361-9cacd7da-cbea-4e0b-89fa-1b184db8da8b.PNG)

**Comment by joannekoch** [comment]
Column headings are defined by EDI, so we cannot change column B heading to middleName, but we can use a middle name in column B.

The new file contents with the addition of Taylor:
![Capture](https://user-images.githubusercontent.com/65416034/220933392-f6810bde-4e72-42d5-8426-41bc764490bc.PNG)

@sbeaulieu, this issue can be closed.

**Comment by sbeaulieu** [comment]
I'll inform Taylor the edit is not possible with the current emlassemblyline templating; it also appears not possible with current EML schema https://eml.ecoinformatics.org/schema/ see "Complex Type Person" "distinct elements do not exist for concepts like "middle name""
