### ISSUE TITLE
change methods file type to markdown

### ISSUE THREAD

**Issue by sbeaulieu** [WHOIGit/minimal-edi-package#5]
related to https://github.com/WHOIGit/ediutilities/issues/9
Having a methods file in this minimal package in markdown format will facilitate the inclusion of methods in markdown format in subsequent packages

**Comment by joannekoch** [comment]
You would not specify the markdown methods file type in the minimal package. You would do it in any other data package. The file type would default to .txt here. There can only be one or the other.

Please delete this issue.

**Comment by sbeaulieu** [comment]
Looks like I can not delete but I will close the issue
